main: net.jandie1505.updatedisplayname.UpdateDisplayName
name: UpdateDisplayName
version: 1.0
api-version: 1.13
author: jandie1505
softdepend:
  - LuckPerms
  - Vault
  - PlaceholderAPI
commands:
  updatedisplayname:
    description: 'plugin command'
    permission: updatedisplayname.command
    aliases: ['udn']
permission:
  updatedisplayname.command:
    description: Access to the plugin command
  updatedisplayname.*:
    description: 'Wildcard Permission'
    children: ['updatedisplayname.command']
